keys:
  - &xiongchenyu 4EDE451FC10722D0C6662C6FB99B8189C7C153F6
  - &yubikey 5AF06033B3CC0104450B4F25F438D971EBE848EE
  - &orangepi age14ucj8huwm2lahh3s9uur8f6lkcpf5u2rqa2xpqkju5785gngkszst8e2kh
  - &roy A0F944EC7545AB828936DB0BA36E15153C496C9D

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *orangepi
        pgp:
          - *xiongchenyu
          - *yubikey
          - *roy
